name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.0'  
          
      - name: Build Project in Backend Directory
        run: |
          cd backend 
          go mod tidy
          go test ./...
          go build -o bin/ecommerceapp ./cmd/ecommerce-api  # เก็บไว้ใน backend/bin

      - name: Verify Binary Exists
        run: ls -la backend/bin  # ตรวจสอบว่าไฟล์ binary อยู่ที่นี่
      - name: location backend
        run: find . -name backend
      - name: cd backend
        run: cd backend/bin && ls -la
      - name: location
        run: pwd

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Show Current Directory
        run: pwd
      
      - name: List Files
        run: cd backend/bin && ls -la # แสดงไฟล์ใน backend/bin
      
      - name: Deploy to Nginx
        run: |
          sudo cp backend/bin/ecommerceapp /var/www/html  # คัดลอกไฟล์ binary ไปยังตำแหน่งที่ Nginx ใช้
          sudo systemctl restart nginx  # รีสตาร์ท Nginx เพื่อให้การเปลี่ยนแปลงมีผล
