name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Create .env file in backend folder
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > ./backend/.env
        
      # 4. Build Backend Docker Image
      - name: Build Backend Image
        run: |
          docker build -t pornlapatp/backend:ci ./backend  # ใช้ชื่อผู้ใช้และ repository ถูกต้อง

      # 5. Build Frontend Docker Image
      - name: Build Frontend Image
        run: |
          docker build -t pornlapatp/frontend:ci ./frontend/frontend  # ใช้ชื่อผู้ใช้และ repository ถูกต้อง

      # 6. Verify Docker Images
      - name: Verify Docker Images
        run: |
          docker images

      # 7. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8. Push Backend Docker Image to Docker Hub
      - name: Push Backend Image to Docker Hub
        run: |
          docker push pornlapatp/backend:ci  # ใช้ชื่อผู้ใช้และ repository ถูกต้อง

      # 9. Push Frontend Docker Image to Docker Hub
      - name: Push Frontend Docker Image to Docker Hub
        run: |
          docker push pornlapatp/frontend:ci  # ใช้ชื่อผู้ใช้และ repository ถูกต้อง
