name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Create .env file
      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
        
      # 4. Build Backend Docker Image
      - name: Build Backend Image
        run: |
          docker build -t backend:ci ./backend

      # 5. Build Frontend Docker Image
      - name: Build Frontend Image
        run: |
          docker build -t frontend:ci ./frontend
