name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Create .env file in backend folder
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > ./backend/.env
        
      # 4. Build Backend Docker Image
      - name: Build Backend Image
        run: |
          docker build -t pornlapatp/backend:ci ./backend  # ใช้ชื่อผู้ใช้และ repository ถูกต้อง

      # 5. Build Frontend Docker Image
      - name: Build Frontend Image
        run: |
          docker build -t pornlapatp/frontend:ci ./frontend/frontend  # ใช้ชื่อผู้ใช้และ repository ถูกต้อง

      # 6. Verify Docker Images
      - name: Verify Docker Images
        run: |
          docker images

      # 7. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8. Push Backend Docker Image to Docker Hub
      - name: Push Backend Image to Docker Hub
        run: |
          docker push pornlapatp/backend:ci  

      # 9. Push Frontend Docker Image to Docker Hub
      - name: Push Frontend Docker Image to Docker Hub
        run: |
          docker push pornlapatp/frontend:ci  

      # 10. SSH to Server and Pull Docker Image for Backend
      - name: SSH to Server and Pull Backend Docker Image
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: 22
          debug: true # เพิ่ม Debugging
          script: |
            docker pull pornlapatp/backend:ci
            docker stop backend-container || true
            docker rm backend-container || true
            docker run -d --name backend-container -p 8080:8080 pornlapatp/backend:ci

      # 11. SSH to Server and Pull Docker Image for Frontend
      - name: SSH to Server and Pull Frontend Docker Image
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull pornlapatp/frontend:ci
            docker stop frontend-container || true
            docker rm frontend-container || true
            docker run -d --name frontend-container -p 80:80 pornlapatp/frontend:ci
