name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Verify Checkout
        run: |
          echo "Current Directory:"
          pwd
          echo "Files in Current Directory:"
          ls -la

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.0'  # ระบุเวอร์ชันของ Go ที่คุณต้องการใช้
          
      - name: Build Project in Backend Directory
        run: |
          cd backend
          mkdir -p bin  # สร้าง directory bin ถ้าไม่มี
          go mod tidy
          go test ./...
          go build -o ./bin/ecommerceapp ./cmd/ecommerce-api
          ls -l ./bin  # แสดงรายละเอียดของไฟล์ใน directory bin

      - name: Verify Binary Exists in Backend Bin
        run: |
          ls -l backend/bin  # ตรวจสอบว่ามีไฟล์ ecommerceapp อยู่ใน directory bin
          file backend/bin/ecommerceapp  # ตรวจสอบประเภทของไฟล์

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: List Root Directory
        run: ls -l

      - name: List Backend Directory
        run: ls -l backend

      - name: List Bin Directory
        run: ls -l backend/bin

        
      - name: Deploy to Nginx
        run: |
          sudo cp backend/bin/ecommerceapp /var/www/html  # คัดลอกไฟล์ binary ไปยังตำแหน่งที่ Nginx ใช้
          sudo systemctl restart nginx  # รีสตาร์ท Nginx เพื่อให้การเปลี่ยนแปลงมีผล
