name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.0'  
          
      - name: List Files in Current Directory
        run: ls -la  # List files to verify the working directory

      - name: Prepare Bin Directory
        run: |
          mkdir -p backend/bin  # Create the bin directory if it doesn't exist

      - name: Build Project in Backend Directory
        run: |
          cd backend 
          echo "Current Directory: $(pwd)"  # Print the current directory
          go mod tidy
          go test ./...
          go build -o bin/ecommerceapp ./cmd/ecommerce-api  # Save the binary in backend/bin

      - name: Verify Binary Exists
        run: |
          echo "Listing files in backend/bin"
          ls -la backend/bin  # Check if the binary file is here
          if [ -f backend/bin/ecommerceapp ]; then
            echo "Binary exists!"
          else
            echo "Binary does not exist!"
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Show Current Directory
        run: pwd
        
      - name: List Files in Root Directory
        run: ls -la  # Check what is in the root directory

      - name: List Files in backend
        run: ls -la backend  # Check if the backend directory exists

      - name: Check for backend/bin Directory
        run: |
          echo "Checking if backend/bin directory exists..."
          if [ -d backend/bin ]; then
            echo "Directory backend/bin exists."
            ls -la backend/bin  # List files in the bin directory
          else
            echo "Directory backend/bin does not exist."
            exit 1
          fi
        
      - name: Deploy to Nginx
        run: |
          echo "Deploying to Nginx..."
          sudo cp backend/bin/ecommerceapp /var/www/html  # Use relative path for the binary
          sudo systemctl restart nginx  # Restart Nginx to apply changes
