name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.0'  # ระบุเวอร์ชันของ Go ที่คุณต้องการใช้
          
      - name: Change Directory to Backend
        run: |
          cd backend && go mod tidy && go test ./... && go build -o ecommerceapp ./cmd/ecommerce-api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Nginx
        run: |
          sudo cp backend/ecommerceapp /var/www/html  # เปลี่ยนเส้นทางให้ตรงกับการตั้งค่า Nginx
          sudo systemctl restart nginx  # รีสตาร์ท Nginx เพื่อให้การเปลี่ยนแปลงมีผล
