name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.0'  
          
      - name: Build Project in Backend Directory
        run: |
          cd backend 
          go mod tidy
          go test ./...
          mkdir -p bin  # สร้าง directory bin หากยังไม่มี
          go build -o bin/ecommerceapp ./cmd/ecommerce-api  # เก็บไว้ใน backend/bin

      - name: Verify Binary Exists
        run: ls -la backend/bin  # ตรวจสอบว่าไฟล์ binary อยู่ที่นี่

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # ทำการ checkout โค้ดในขั้นตอน deployment

      - name: Show Current Directory
        run: pwd
        
      - name: List Files in backend
        run: ls -la backend  # ตรวจสอบว่า directory backend มีอยู่

      - name: List Files in backend/bin
        run: ls -la backend/bin  # ตรวจสอบว่า directory bin มีอยู่
        
      - name: Deploy to Nginx
        run: |
          sudo cp backend/bin/ecommerceapp /var/www/html  # ใช้ path ที่ relative
          sudo systemctl restart nginx  # รีสตาร์ท Nginx เพื่อให้การเปลี่ยนแปลงมีผล 
