name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.0'  
          
      - name: Build Project in Backend Directory
        run: |
          cd backend || exit 1
          mkdir -p bin  # สร้าง directory bin ถ้าไม่มี
          go mod tidy
          go test ./...
          go build -o ./bin/ecommerceapp ./cmd/ecommerce-api

      - name: Verify Binary Exists in Backend Bin
        run: ls -la backend/bin  # ตรวจสอบว่าไฟล์ ecommerceapp อยู่ใน directory bin

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Show Current Directory
        run: pwd
        
      - name: List Files in Current Directory
        run: ls -la
        
      - name: Deploy to Nginx
        run: |
          sudo cp backend/bin/ecommerceapp /var/www/html  # คัดลอกไฟล์ binary ไปยังตำแหน่งที่ Nginx ใช้
          sudo systemctl restart nginx  # รีสตาร์ท Nginx เพื่อให้การเปลี่ยนแปลงมีผล
