name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Verify Checkout
        run: |
          echo "Current Directory:"
          pwd
          echo "Files in Current Directory:"
          ls -la  # แสดงไฟล์ทั้งหมดใน directory ปัจจุบัน

      - name: Check Parent Directory Structure
        run: |
          echo "Files in Parent Directory:"
          ls -la ..  # แสดงไฟล์ใน parent directory เพื่อดูว่า backend มีอยู่หรือไม่
    
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.0'
          
      - name: Build Project in Backend Directory
        run: |
          cd backend || exit 1
          mkdir -p bin  # สร้าง directory bin ถ้าไม่มี
          go mod tidy
          go test ./...
          go build -o ./bin/ecommerceapp ./cmd/ecommerce-api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check Directory Structure
        run: |
          echo "Current Directory:"
          pwd
          echo "Files in Current Directory:"
          ls -la
          echo "Checking backend directory:"
          ls -la backend  # ตรวจสอบว่า backend directory มีอยู่หรือไม่

      - name: Verify Binary Exists in Backend Bin
        run: |
          cd backend || exit 1
          ls bin  # ตรวจสอบว่ามีไฟล์ ecommerceapp อยู่ใน directory bin

      - name: Deploy to Nginx
        run: |
          cd backend || exit 1
          sudo cp bin/ecommerceapp /var/www/html  # คัดลอกไฟล์ binary ไปยังตำแหน่งที่ Nginx ใช้
          sudo systemctl restart nginx  # รีสตาร์ท Nginx เพื่อให้การเปลี่ยนแปลงมีผล
